import Head from 'next/head';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import Collections from '../components/Trending';
import WorkProcess from '../components/WorkProcess';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>AvatarMarket - Digital Marketplace for Reddit NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Collections />
      <WorkProcess />
      <Footer />
    </div>
  )
}
